version: '3.8'
services:
  # Container [1] mysql container for local development
  # not using a remote database. 
  # staging and production is using Aurora default.aurora5.6
  db:
    #
    image: mysql:5.7
    restart: always
    # allow persisted data
    volumes: 
      - ./db_data:/var/lib/mysql
    # environment variables for now 
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress 
      MYSQL_USER: wordpress 
      MYSQL_PASSWORD: wordpress 
    networks:
      - wp
  # Container [2] Wordpress currently in production, see k8s/podcast/staging 
  wordpress:
    depends_on: 
      - db
    # using the image referenced in k8s
    image: wordpress:latest
    restart: always
    # Maps local folder, to path in a container
    # Useful for file edits, consider mapping only wp-content 
    volumes: ["./wordpress-content:/var/www/html/"]
    # Add environment variables for now
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress 
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress 
    # Ports mapping
    # will be using 9000 series to avoid conflicts with other projects.
    ports:
      - 9000:80
      - 9443:443
    networks:
      - wp
  # Container [3] Adding this container for db debugging purposes
  # it runs on localhost:9090 or 127.0.0.1:/9090
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9090:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wp
# All networks used for this service
networks:
  wp:

## Uncomment to use persistent volumes instead.
# All volumes used for this service
# volumes:
#  ./db_data: {}
#  ./wordpress-content: {}
